create table public.kid_ideas (
  id bigint generated by default as identity not null,
  created_on timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  student_name text null,
  startup_desc text null,
  startup_idea text null,
  startup_logo text null,
  problem_statement text null,
  solution text null,
  likes bigint not null default '0'::bigint,
  rating real not null default '0'::real,
  views bigint not null default '0'::bigint,
  constraint kid_ideas_pkey primary key (id)
) TABLESPACE pg_default;